#!/usr/bin/env bash

first_node=consul-server-1
nodes=( consul-server-2 consul-server-3 vault-server-1 vault-server-2 nomad-server-1 nomad-server-2 nomad-server-3 nomad-client-1 nomad-client-2 nomad-client-3 )

echo "🚚 Deploying consul to /opt/consul/bin on first node..."
  scp consul root@$first_node:/opt/consul/bin/consul-$1

echo "🚚 Deploying consul to /opt/consul/bin on other nodes..."
I=0
for Node in "${nodes[@]}"
do
  echo " - 📦 ${Node}"
  scp root@$first_node:/opt/consul/bin/consul-$1 root@${Node}:/opt/consul/bin/consul-$1 &
  pids[${I}]=$!
  let "I++"
done

echo "⌛️ Waiting for PIDs to complete"
for pid in ${pids[*]}
do
  echo " - ⏰ Waiting for PID $pid"
  wait $pid;
done;
