#! /bin/bash

first_node=10.0.0.52
nodes=( 10.0.0.24 10.0.0.159 10.0.0.174 10.0.0.28 10.0.0.89 10.0.0.208 10.0.0.237 10.0.0.172 10.0.0.26 10.0.0.128 )

echo "🚚 Deploying consul to /opt/consul/bin on first node..."
  scp consul root@$first_node:/opt/consul/bin/consul-$1 

echo "🚚 Deploying consul to /opt/consul/bin on other nodes..."
I=0
for Node in "${nodes[@]}"
do
  echo " - 📦 ${Node}"
  scp root@$first_node:/opt/consul/bin/consul-$1 root@${Node}:/opt/consul/bin/consul-$1 &
  pids[${I}]=$!
  let "I++"
done

echo "⌛️ Waiting for PIDs to complete"
for pid in ${pids[*]}
do 
  echo " - ⏰ Waiting for PID $pid"
  wait $pid; 
done;
