#! /bin/bash

if [[ "${NOMAD_ADDR}" = "" ]]
then 
	Address="http://127.0.0.1:4646"
else 
	Address=${NOMAD_ADDR}
fi


if [[ $# -eq 1 && "-s" = "${1}" ]]
then
   silent=true
else 
   slient=false
fi

if [[ $# -ge 1 && "-s" != "${1}" ]]
then
   echo "Usage:"
   echo "  -s - Run with no output"
   exit 1
fi

function print {
  if [[ ${silent} != "true" ]]
  then 
    echo $@
  fi
}

print -n "Running Nomad GC..."
curl -s -XPUT ${Address}/v1/system/gc
if [[ $? -eq 0 ]]
then
	print " Done."
else
	print " Error."
	curl -XPUT ${Address}/v1/system/gc
fi
